<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Kiln.Render.OpenGL</RootNamespace>
        <AssemblyName>Kiln.Render.OpenGL</AssemblyName>
        <Description>OpenGL rendering backend for KilnEngine</Description>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    </ItemGroup>

</Project>